name: fluiver
description: A comprehensive Flutter toolkit with expressive extensions, versatile widgets and useful helpers.
version: 2.4.1
homepage: https://mehmetesen.com
repository: https://github.com/esenmx/fluiver
issue_tracker: https://github.com/esenmx/fluiver/issues

topics:
  - extensions
  - utilities
  - helpers
  - widgets
  - productivity

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.10.4
  checks: ^0.3.1
  fake_async: ^1.3.3
  flutter_test:
    sdk: flutter
  mockito: ^5.6.1
  very_good_analysis: ^10.0.0
